name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    timeout-minutes: 60
    # env:
    #   DEVELOPER_DIR: /Applications/Xcode_??.app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # - name: Cache node modules
      #   uses: actions/cache@v3
      #   id: cache
      #   with:
      #     path: node_modules
      #     key: node_modules-${{ hashFiles('**/yarn.lock') }}

      # - name: Rebuild detox
      #   # if: steps.cache.outputs.cache-hit == 'true'
      #   run: detox clean-framework-cache && detox build-framework-cache

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      # Should save around 5 minutes from "Update Pods"
      - name: Cache Pods
        uses: actions/cache@v3
        id: podcache
        with:
          path: ios/Pods
          key: pods-${{ hashFiles('**/Podfile.lock') }}

      # TODO: see how fast this is, but might have to cache more if you're updating the native projects
      - name: Cache iOS Build Folder
        uses: actions/cache@v3
        id: ioscache
        with:
          path: ios/build
          key: ios-${{ hashFiles('**/Podfile.lock') }}

      - name: Update Pods
        run: |
          gem update cocoapods xcodeproj
          cd ios && pod install && cd ..

      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run: yarn detox build e2e --configuration ios.sim.release
      - run: yarn detox test e2e --configuration ios.sim.release --cleanup --debug-synchronization 200
